### PR TITLE
:seedling: TK-7144 Refactor Preflight Unit and Integration test suite

### PR DESCRIPTION
**Pull request by prasad-trilio**
Converted some intgeration tests into unit-test.

Removed dependency on `pre-build` job for preflight and log-collector tests jobs.

### CODE REVIEW

**Review by somesh22123 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/trilioData/tvk-plugins/160)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @prasad-trilio)

___
*[`cmd/preflight/cmd/run.go` line 53 at r1](https://reviewable.io/reviews/trilioData/tvk-plugins/160#-NOPOoua0UvPJRfm9XWi:-NOPOoua0UvPJRfm9XWj:b3hvdj0) ([raw file](https://github.com/trilioData/tvk-plugins/blob/b68738937f03d84dcbd44b71a6c708ef2a014e88/cmd/preflight/cmd/run.go#L53)):*
> ```Go
> `,
> 	RunE: func(cmd *cobra.Command, args []string) (err error) {
> 		var preflightLogFilename string
> ```

no changes/enhancements in file, can be reverted with except for import grouping.
___
*[`tests/preflight/preflight_test.go` line 383 at r1](https://reviewable.io/reviews/trilioData/tvk-plugins/160#-NOPNd7h0qofUn4TqrCK:-NOPNd7h0qofUn4TqrCL:b-5jozjl) ([raw file](https://github.com/trilioData/tvk-plugins/blob/b68738937f03d84dcbd44b71a6c708ef2a014e88/tests/preflight/preflight_test.go#L383)):*
> ```Go
> 			})
> 
> 			It("Should not perform preflight checks if file contains invalid keys or invalid key hierarchy", func() {
> ```

removed test case is missing in unit test cases.

**Comment by somesh22123** [comment]
@prasad-trilio we should increase the timeout interval for failed test cases.

**Comment by prasad-trilio** [comment]
> removed test case is missing in unit test cases

The relevant test-case was already present in `cmd/preflight/cmd/helper_test.go`. 
The test case is 
```go
	It("Should return error when input data format does not match with struct variable fields "+
			"or contains incorrect hierarchy of field values", func() {
```
It does not appear in diff changes.

**Comment by prasad-trilio** [comment]
> no changes/enhancements in file, can be reverted with except for import grouping.

moved the func call `preflight.InitKubeEnv(cmdOps.Run.Kubeconfig)` below the logger initialization. So that, any error during kube clients creation gets logged into the log-file.

**Comment by prasad-trilio** [comment]
> @prasad-trilio we should increase the timeout interval for failed test cases.

for `cleanup` command test-cases, in code we are performing delete operation and then updating the object to remove finalizers. This might cause the test to fail. for `run` command, volume-snapshot does not come in ready state, a timeout of  10min already exists.

**Review by somesh22123 — APPROVED** [review]
LGTM

**Pull request merged**
