### PR TITLE
🐛fix: Fix the logic to get the default volumeSnapshotClass

### LINKED ISSUE #166: bug(preflight): Default VolumeSnapshotClass is not recognized in
## Problem
Preflight check without mentiong the default VSC(VolumeSnapshotClass) selects the VSC whose name is last in alphabetic.

## Expecation
Default VSC should be selected when the VSC is not specified in run command.

### PR DESCRIPTION
**Pull request by josedev-union**
fix #166

### CODE REVIEW

**Comment by prasad-trilio** [comment]
@josedev-union can you please check the CI job failures.

**Comment by josedev-union** [comment]
> @josedev-union can you please check the CI job failures.

i checked but seems not related to my change?

**Comment by prasad-trilio** [comment]
@josedev-union there is one go lint failure due to your changes. Can you please fix that

Regarding the test job execution failures, due to organization restrictions, it won't be possible to run the jobs on this PR.
We will raise a parallel PR with changes exactly same as yours, only to monitor the job status over there. But, this PR will be merged when everything looks good.
In this way, we will preserve your contribution and monitor the jobs as well.

**Comment by josedev-union** [comment]
> @josedev-union there is one go lint failure due to your changes. Can you please fix that
> 
> Regarding the test job execution failures, due to organization restrictions, it won't be possible to run the jobs on this PR. We will raise a parallel PR with changes exactly same as yours, only to monitor the job status over there. But, this PR will be merged when everything looks good. In this way, we will preserve your contribution and monitor the jobs as well.

@prasad-trilio thanks for this information. I tried to fix lll lint error. I ran the same lint command on my local and passed. Could you run CI again?

**Comment by prasad-trilio** [comment]
A parallel PR has been raised [here](https://github.com/trilioData/tvk-plugins/pull/168)

**Review by prasad-trilio — APPROVED** [review]

**Comment by prasad-trilio** [comment]
10/26 tests are failing. The tests need to be modified according to the changes done in this PR.
We are tracking the progress of test-cases work [here](https://github.com/trilioData/tvk-plugins/issues/170)

**Comment by prasad-trilio** [comment]
thanks @josedev-union

**Pull request merged**
